spring:
  application:
    name: store

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    secret: ${JWT_SECRET}
    TimeOutR: ${Refresh_Token_Expire}
    TimeOutA: ${Access_Token_Expire}

  profiles:
    active: dev

  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

server:
  forward-headers-strategy: framework
