spring:
  application:
    name: store

  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    secret: ${JWT_SECRET}
    TimeOutR: ${Refresh_Token_Expire}
    TimeOutA: ${Access_Token_Expire}

  stripe:
    secretKey: ${STRIPE_SECRET_KEY}

  webSiteUrl: "https://dorthey-unlosable-irrecoverably.ngrok-free.dev/:8080"
